name: Cypress Tests

on:
  schedule:
    - cron: "0 6 * * *"

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.14.2-slim-chrome103-ff102
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4.2.0
        with:
          build: npm i -D cypress
          browser: chrome
