name: Selenium Tests

on:
  push:
    branches:
      - development_selenium
  schedule:
    - cron: "0 6 * * *"

jobs:
  selenium-run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install software
        uses: browser-actions/setup-chrome@latest
        run: chrome --version
      - name: Install the necessary packages
        run: pip install selenium pytest webdriver-manager
      - name: Run the PytTest script
        run: python3 -m pytest